export type OntologyAttribute = {
  stableKey: string;
  category: string;
  label: string;
  definition: string;
  moralValence: "good" | "evil" | "neutral";
};

const definitions: ReadonlyArray<readonly [string, string, string, OntologyAttribute["moralValence"]]> = [
  ["aesthetic.elegant", "優美・洗練", "aesthetic", "neutral"],
  ["aesthetic.cute", "かわいさ", "aesthetic", "neutral"],
  ["aesthetic.beautiful", "美しさ", "aesthetic", "neutral"],
  ["aesthetic.grotesque", "異形・グロテスク", "aesthetic", "neutral"],
  ["aesthetic.nonhuman", "非人間的造形", "aesthetic", "neutral"],
  ["aesthetic.intimidating", "威圧的造形", "aesthetic", "neutral"],
  ["aesthetic.ordinary", "平凡・目立たない造形", "aesthetic", "neutral"],
  ["speech.refined", "上品・洗練された話し方", "speech", "neutral"],
  ["speech.rough", "荒い話し方", "speech", "neutral"],
  ["speech.playful", "戯画的・遊戯的な話し方", "speech", "neutral"],
  ["speech.sparse", "寡黙", "speech", "neutral"],
  ["speech.theatrical", "芝居がかった表現", "speech", "neutral"],
  ["personality.kind", "親切", "personality", "neutral"],
  ["personality.cold", "冷淡", "personality", "neutral"],
  ["personality.arrogant", "傲慢", "personality", "neutral"],
  ["personality.cunning", "狡猾", "personality", "neutral"],
  ["personality.honest", "率直・誠実", "personality", "neutral"],
  ["personality.deceptive", "欺瞞的", "personality", "neutral"],
  ["personality.obsessive", "執着的", "personality", "neutral"],
  ["personality.unapologetic", "悪びれない", "personality", "neutral"],
  ["personality.capricious", "気まぐれ", "personality", "neutral"],
  ["personality.detached", "超然・感情的距離", "personality", "neutral"],
  ["warmth.compassionate", "思いやり", "warmth_trust", "neutral"],
  ["warmth.selective", "選択的な優しさ", "warmth_trust", "neutral"],
  ["warmth.indifferent", "他者への無関心", "warmth_trust", "neutral"],
  ["trust.loyal", "忠実", "warmth_trust", "neutral"],
  ["trust.betraying", "裏切り", "warmth_trust", "neutral"],
  ["agency.proactive", "主体的", "agency_ability", "neutral"],
  ["agency.dominant", "支配的", "agency_ability", "neutral"],
  ["agency.submissive", "服従的", "agency_ability", "neutral"],
  ["ability.powerful", "強大な力", "agency_ability", "neutral"],
  ["ability.intelligent", "知性", "agency_ability", "neutral"],
  ["ability.strategic", "戦略性", "agency_ability", "neutral"],
  ["ability.incompetent", "無能・不器用", "agency_ability", "neutral"],
  ["motivation.ambition", "野心", "motivation", "neutral"],
  ["motivation.revenge", "復讐", "motivation", "neutral"],
  ["motivation.control", "支配欲", "motivation", "neutral"],
  ["motivation.destruction", "破壊欲", "motivation", "neutral"],
  ["motivation.survival", "生存欲", "motivation", "neutral"],
  ["motivation.belonging", "所属欲求", "motivation", "neutral"],
  ["motivation.no_grand_goal", "大目的を持たない", "motivation", "neutral"],
  ["morality.heroic", "英雄的方向性", "value_morality", "good"],
  ["morality.antiheroic", "反英雄的方向性", "value_morality", "neutral"],
  ["morality.villainous", "悪役的方向性", "value_morality", "evil"],
  ["morality.evil", "悪そのものへの志向", "value_morality", "evil"],
  ["morality.immoral", "非道徳", "value_morality", "evil"],
  ["morality.amoral", "道徳を判断軸にしない", "value_morality", "neutral"],
  ["morality.transgressive", "規範逸脱", "value_morality", "neutral"],
  ["morality.self_defined", "自己定義の規範", "value_morality", "neutral"],
  ["morality.hypocritical", "道徳的偽善", "value_morality", "neutral"],
  ["goodness.indifferent", "善への無関心", "goodness_relation", "neutral"],
  ["goodness.hostile", "善への敵対", "goodness_relation", "neutral"],
  ["goodness.instrumental", "善を手段として扱う", "goodness_relation", "neutral"],
  ["evil.affirms", "悪を肯定する", "goodness_relation", "evil"],
  ["evil.enjoys_cruelty", "残酷さを楽しむ", "goodness_relation", "evil"],
  ["redemption.seeks", "改心・贖罪を求める", "goodness_relation", "neutral"],
  ["redemption.refuses", "改心・贖罪を拒む", "goodness_relation", "neutral"],
  ["redemption.irrelevant", "改心を問題にしない", "goodness_relation", "neutral"],
  ["vulnerability.fragile", "脆さ", "vulnerability", "neutral"],
  ["vulnerability.lonely", "孤独", "vulnerability", "neutral"],
  ["vulnerability.fearful", "恐れ", "vulnerability", "neutral"],
  ["vulnerability.none_shown", "脆弱性を見せない", "vulnerability", "neutral"],
  ["duality.masked", "仮面・表裏", "duality_conflict", "neutral"],
  ["duality.conflicted", "内的葛藤", "duality_conflict", "neutral"],
  ["duality.inconsistent", "矛盾・不整合", "duality_conflict", "neutral"],
  ["duality.single_minded", "一貫・迷いのなさ", "duality_conflict", "neutral"],
  ["relationship.protective", "保護的", "relationship", "neutral"],
  ["relationship.possessive", "所有・独占的", "relationship", "neutral"],
  ["relationship.manipulative", "操作的", "relationship", "neutral"],
  ["relationship.rivalrous", "競争・宿敵", "relationship", "neutral"],
  ["relationship.isolated", "孤立", "relationship", "neutral"],
  ["relationship.devoted", "献身", "relationship", "neutral"],
  ["role.hero", "ヒーロー", "narrative_role", "neutral"],
  ["role.villain", "ヴィラン", "narrative_role", "neutral"],
  ["role.antihero", "アンチヒーロー", "narrative_role", "neutral"],
  ["role.antagonist", "敵対者", "narrative_role", "neutral"],
  ["role.supporting", "脇役", "narrative_role", "neutral"],
  ["role.minor", "端役", "narrative_role", "neutral"],
  ["role.scene_limited", "一場面限定", "narrative_role", "neutral"],
  ["role.comic_relief", "コミックリリーフ", "narrative_role", "neutral"],
  ["role.observer", "観察者", "narrative_role", "neutral"],
  ["change.growth", "成長", "change_outcome", "neutral"],
  ["change.corruption", "堕落", "change_outcome", "neutral"],
  ["change.flat", "変化しない", "change_outcome", "neutral"],
  ["change.no_redemption", "改心しない", "change_outcome", "neutral"],
  ["outcome.victory", "勝利", "change_outcome", "neutral"],
  ["outcome.defeat", "敗北", "change_outcome", "neutral"],
  ["outcome.unpunished", "罰されない", "change_outcome", "neutral"],
  ["tone.comedic", "コメディ的", "expression_tone", "neutral"],
  ["tone.horrific", "恐怖的", "expression_tone", "neutral"],
  ["tone.tragic", "悲劇的", "expression_tone", "neutral"],
  ["tone.camp", "誇張・キャンプ", "expression_tone", "neutral"],
  ["tone.understated", "控えめ・静的", "expression_tone", "neutral"],
  ["tone.menacing", "脅威的", "expression_tone", "neutral"],
];

export const standardOntology: OntologyAttribute[] = definitions.map(([stableKey, label, category, moralValence]) => ({
  stableKey,
  label,
  category,
  moralValence,
  definition: `${label}を表す統制属性。`,
}));
