-- Generated by npm run assets:generate from shared/catalogs. Do not edit.
INSERT INTO attribute_schema_versions (id,version,status,description,content_hash,published_at,created_at,analysis_domain)
VALUES ('e32dc400-a975-5cf5-aedd-9ea4f20aeb87','1.0','active','初期統制語彙','b1994499feb3d38c90a4fb0a44e0ce7c144b0aa2b16dbe6879a0c7bc50f42675','2026-08-29T00:00:00.000Z','2026-08-29T00:00:00.000Z','standard');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('be4b6b76-bf3f-5281-a7ad-94a3fca8ed8f','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.elegant','aesthetic','優美・洗練','優美・洗練を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('682bc935-4609-5186-ad83-0dc4051c0c74','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.cute','aesthetic','かわいさ','かわいさを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('28ebacc1-bbb1-580a-a062-d09e56fb3d1f','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.beautiful','aesthetic','美しさ','美しさを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('e2533df7-d0c8-5d96-a90c-b1b988d40b66','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.grotesque','aesthetic','異形・グロテスク','異形・グロテスクを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('1e4c78f9-c695-5026-a434-383841e52dc0','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.nonhuman','aesthetic','非人間的造形','非人間的造形を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('24ea8719-5866-592a-a92c-4546b7dc7d40','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.intimidating','aesthetic','威圧的造形','威圧的造形を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9519491e-c414-571f-ad2d-332e98cdc133','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','aesthetic.ordinary','aesthetic','平凡・目立たない造形','平凡・目立たない造形を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('4f149a41-787e-509f-a5fd-4a0249ecf370','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','speech.refined','speech','上品・洗練された話し方','上品・洗練された話し方を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('084216d4-8356-559b-a5c0-a91d08378828','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','speech.rough','speech','荒い話し方','荒い話し方を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('24806fdf-715a-522a-adfc-fb4ab550d305','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','speech.playful','speech','戯画的・遊戯的な話し方','戯画的・遊戯的な話し方を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('c7d07acd-dc4b-5e35-a4da-cd8d314c1efe','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','speech.sparse','speech','寡黙','寡黙を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('e431c7c2-061d-5742-a004-8f19efbb71df','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','speech.theatrical','speech','芝居がかった表現','芝居がかった表現を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('344d9ade-447b-5949-aa82-fc3227752dcc','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.kind','personality','親切','親切を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('fcc8ae61-909f-57a6-a9da-421c62419b1a','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.cold','personality','冷淡','冷淡を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('cf151cb9-31fe-56ec-ab99-191fcd530099','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.arrogant','personality','傲慢','傲慢を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('1af43428-8d82-500b-aebe-6bceba0e842a','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.cunning','personality','狡猾','狡猾を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('2c019815-5cf9-527f-a7e0-851da75fd1eb','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.honest','personality','率直・誠実','率直・誠実を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('d320701e-8a07-5f0a-afd6-caa292fceac8','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.deceptive','personality','欺瞞的','欺瞞的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('d7f9cad8-c156-5af0-a4e1-f2949e1eb006','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.obsessive','personality','執着的','執着的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5858db2d-7873-5afe-af49-f54a99faf450','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.unapologetic','personality','悪びれない','悪びれないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9ebc2c40-8aab-5c68-ae5c-bbf1b4247eac','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.capricious','personality','気まぐれ','気まぐれを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5fff6eb5-69c5-5120-a386-393655611fb8','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','personality.detached','personality','超然・感情的距離','超然・感情的距離を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('774b29e7-5769-5b84-aa4e-872b763115c9','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','warmth.compassionate','warmth_trust','思いやり','思いやりを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('e1b0079d-2eed-56d9-a324-808d0069d11b','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','warmth.selective','warmth_trust','選択的な優しさ','選択的な優しさを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('2cc41057-2c00-5c97-aad4-2a2e1cef2079','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','warmth.indifferent','warmth_trust','他者への無関心','他者への無関心を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('241e3b77-8515-5f90-acdc-ce5184cccf62','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','trust.loyal','warmth_trust','忠実','忠実を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('c3ea6347-9579-5950-a130-e44abc06763a','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','trust.betraying','warmth_trust','裏切り','裏切りを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('a1fc849b-0d6f-5a86-a0a1-bda0b3e34ceb','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','agency.proactive','agency_ability','主体的','主体的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('f1b1fcf9-ca97-5414-af0d-b81a21730a95','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','agency.dominant','agency_ability','支配的','支配的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('56843823-3a8b-5670-aaf4-1d4333fab443','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','agency.submissive','agency_ability','服従的','服従的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('0b92f826-bab9-5f67-a16c-9a2f8d7c8cc0','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','ability.powerful','agency_ability','強大な力','強大な力を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('7c6290f8-a4ab-5d77-a83f-34b4ca8630c9','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','ability.intelligent','agency_ability','知性','知性を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('c821fa24-f8c7-54d5-af76-469a4092c48a','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','ability.strategic','agency_ability','戦略性','戦略性を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('3a378f91-17a8-5038-a756-57eb8155eca0','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','ability.incompetent','agency_ability','無能・不器用','無能・不器用を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('d8a20328-c884-5500-a5db-1d16ca07504b','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.ambition','motivation','野心','野心を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9e716963-3f02-5f00-aeab-a7f701bd781f','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.revenge','motivation','復讐','復讐を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('dad9d1fe-2e60-50d4-afa5-467f8f20cf23','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.control','motivation','支配欲','支配欲を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5f0fd012-5022-5da8-a608-30211e8a88c4','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.destruction','motivation','破壊欲','破壊欲を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5716bf56-8f21-5601-a575-cd4e31ce8797','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.survival','motivation','生存欲','生存欲を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('d9ea782f-6a0a-5670-a7ca-ad24eb9ca36d','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.belonging','motivation','所属欲求','所属欲求を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9efd9dd1-368d-5d5c-a61e-0cd4b9adbf90','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','motivation.no_grand_goal','motivation','大目的を持たない','大目的を持たないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('cb9253e2-ad8c-5af6-a6bb-559ad56db0af','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.heroic','value_morality','英雄的方向性','英雄的方向性を表す統制属性。','managed','good','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('6d4f897f-e656-562b-a8a6-2406f8da9391','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.antiheroic','value_morality','反英雄的方向性','反英雄的方向性を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('c67584d5-9cec-5b81-a35a-e00cd8074a5c','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.villainous','value_morality','悪役的方向性','悪役的方向性を表す統制属性。','managed','evil','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('7e02afe0-c262-5922-a308-d863a4c19563','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.evil','value_morality','悪そのものへの志向','悪そのものへの志向を表す統制属性。','managed','evil','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('46af94cf-a96d-5d79-a54c-71e29216d05a','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.immoral','value_morality','非道徳','非道徳を表す統制属性。','managed','evil','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('58440412-20db-50fc-a67c-2420d80e9df5','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.amoral','value_morality','道徳を判断軸にしない','道徳を判断軸にしないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5ee08344-aa03-5e93-aace-6aa387ecdd34','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.transgressive','value_morality','規範逸脱','規範逸脱を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5837d021-270e-5e1b-a64b-f7457c0e31d6','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.self_defined','value_morality','自己定義の規範','自己定義の規範を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('47a571fc-c865-5e7b-a488-04e231a0e5a3','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','morality.hypocritical','value_morality','道徳的偽善','道徳的偽善を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('3a64f31a-9b3c-5726-ac79-21aab1120f57','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','goodness.indifferent','goodness_relation','善への無関心','善への無関心を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('a30e84cd-d036-52b3-a4ed-22511941551c','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','goodness.hostile','goodness_relation','善への敵対','善への敵対を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('91379880-0fad-566d-a287-99ff8b813637','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','goodness.instrumental','goodness_relation','善を手段として扱う','善を手段として扱うを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('607524b6-5a62-5f18-a34d-74f7423e61e7','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','evil.affirms','goodness_relation','悪を肯定する','悪を肯定するを表す統制属性。','managed','evil','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('7f34d745-b0c3-57f4-a86b-3a1b9a9230b7','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','evil.enjoys_cruelty','goodness_relation','残酷さを楽しむ','残酷さを楽しむを表す統制属性。','managed','evil','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('cb3fa397-dc13-54af-ac50-2cc23f3937da','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','redemption.seeks','goodness_relation','改心・贖罪を求める','改心・贖罪を求めるを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('82fefa93-0a04-54ed-ad02-22e7003e4d77','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','redemption.refuses','goodness_relation','改心・贖罪を拒む','改心・贖罪を拒むを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9587a534-7223-53e4-a995-57e707efde51','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','redemption.irrelevant','goodness_relation','改心を問題にしない','改心を問題にしないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('960f9d6a-e1dd-5ab8-a340-afa5366b45ed','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','vulnerability.fragile','vulnerability','脆さ','脆さを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('4d8728f0-5543-5fba-aaa6-c4bca96cfbf8','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','vulnerability.lonely','vulnerability','孤独','孤独を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5000a0ec-d01f-53fa-ab2c-b1b962327746','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','vulnerability.fearful','vulnerability','恐れ','恐れを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('8f1e79f2-0864-501e-add5-3a34eb41f88e','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','vulnerability.none_shown','vulnerability','脆弱性を見せない','脆弱性を見せないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('2d5673bf-5edf-5eed-ae35-857904e22dc8','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','duality.masked','duality_conflict','仮面・表裏','仮面・表裏を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('a9962c84-e3f0-5c56-a657-e01371dff5d4','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','duality.conflicted','duality_conflict','内的葛藤','内的葛藤を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('e0ca2356-63ee-5d9e-a558-d48c85bc5e1b','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','duality.inconsistent','duality_conflict','矛盾・不整合','矛盾・不整合を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('d4c1ec11-82e4-5fe4-aee1-f2f1e066b7dc','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','duality.single_minded','duality_conflict','一貫・迷いのなさ','一貫・迷いのなさを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('41487d63-d3b6-5511-a7d9-c09f3aa2b792','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','relationship.protective','relationship','保護的','保護的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('bec2d31b-b3fa-5eb3-a34f-51f0c897c91a','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','relationship.possessive','relationship','所有・独占的','所有・独占的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('da146046-d279-5606-abb7-55a7d809ab23','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','relationship.manipulative','relationship','操作的','操作的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('44688ae9-bdd0-5cb7-a06a-0fbf24533c14','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','relationship.rivalrous','relationship','競争・宿敵','競争・宿敵を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('ed498940-0083-5af0-a4e7-d9b72f511184','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','relationship.isolated','relationship','孤立','孤立を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('a5574a59-a3df-59bc-ab12-c07e40fd93f3','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','relationship.devoted','relationship','献身','献身を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('ca8d55a5-24f6-58f5-ad88-571850a87eba','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.hero','narrative_role','ヒーロー','ヒーローを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('04ee12a1-a307-506a-a395-56e5680c6df2','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.villain','narrative_role','ヴィラン','ヴィランを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('7bee9a62-a863-5f5d-a9ec-91fe2f588285','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.antihero','narrative_role','アンチヒーロー','アンチヒーローを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('5b4e725c-65bf-504b-abb8-7f30e05f4cb0','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.antagonist','narrative_role','敵対者','敵対者を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('897fbc47-e4cb-5775-a255-241f665c18df','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.supporting','narrative_role','脇役','脇役を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('f0577448-0aec-58fe-a6e8-5eca98c05ffa','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.minor','narrative_role','端役','端役を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9b1158d2-a082-5062-a39a-ccd7ad473909','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.scene_limited','narrative_role','一場面限定','一場面限定を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('8042123b-dad6-5f4f-a77b-97d28afab45b','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.comic_relief','narrative_role','コミックリリーフ','コミックリリーフを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('879912c8-ad3a-57ac-ad42-e662bea6823e','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','role.observer','narrative_role','観察者','観察者を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('b10a8089-61db-5fcf-ac86-4bc911b0514d','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','change.growth','change_outcome','成長','成長を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('e3255fb0-452d-58c7-a7d9-4db5cb281612','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','change.corruption','change_outcome','堕落','堕落を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('173a6fb4-115b-52fb-af95-2bc1c5092967','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','change.flat','change_outcome','変化しない','変化しないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('83cef5b9-f343-5795-af2b-3190cf24a692','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','change.no_redemption','change_outcome','改心しない','改心しないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('0addee59-63d5-5bd8-a4d8-491ec11dcf24','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','outcome.victory','change_outcome','勝利','勝利を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('403b4a75-c3d2-524c-a50c-5b9d01fa1808','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','outcome.defeat','change_outcome','敗北','敗北を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('1806c558-5b53-53ab-aac1-44f051c0bf21','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','outcome.unpunished','change_outcome','罰されない','罰されないを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('3313da62-1229-572c-a3f0-9fe748ec99c3','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','tone.comedic','expression_tone','コメディ的','コメディ的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('9237cc29-c8d9-57c9-a6a9-0beb2359bfbf','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','tone.horrific','expression_tone','恐怖的','恐怖的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('a1ebfd0c-b9b4-57d0-a8db-998de99e0c14','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','tone.tragic','expression_tone','悲劇的','悲劇的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('fd910308-12ba-5e7c-aa08-21f752ab0938','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','tone.camp','expression_tone','誇張・キャンプ','誇張・キャンプを表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('65de47ca-8cec-5546-a7eb-e8231ef3a2dd','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','tone.understated','expression_tone','控えめ・静的','控えめ・静的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

INSERT INTO attribute_definitions (id,schema_version_id,stable_key,category,label,definition,vocabulary_tier,moral_valence,status,created_at)
VALUES ('ad56ddc6-ca47-5afc-af7c-06935e8fbec4','e32dc400-a975-5cf5-aedd-9ea4f20aeb87','tone.menacing','expression_tone','脅威的','脅威的を表す統制属性。','managed','neutral','active','2026-08-29T00:00:00.000Z');

