-- Preserve candidate IDs and supersession links while allowing an unresolved response channel.
CREATE TABLE preference_assertions_new (
  id TEXT PRIMARY KEY,
  owner_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  analysis_run_id TEXT NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
  entry_revision_id TEXT NOT NULL REFERENCES entry_revisions(id) ON DELETE CASCADE,
  character_identity_id TEXT NOT NULL REFERENCES character_identities(id) ON DELETE RESTRICT,
  representation_id TEXT NOT NULL REFERENCES character_representations(id) ON DELETE RESTRICT,
  attribute_definition_id TEXT REFERENCES attribute_definitions(id) ON DELETE SET NULL,
  raw_mention_id TEXT REFERENCES raw_attribute_mentions(id) ON DELETE SET NULL,
  analysis_domain TEXT NOT NULL DEFAULT 'standard' CHECK (analysis_domain IN ('standard','dark')),
  polarity TEXT NOT NULL CHECK (polarity IN ('positive','negative','mixed')),
  response_channel TEXT CHECK (response_channel IN (
    'person_liking',
    'aesthetic_liking',
    'voice_performance_liking',
    'narrative_interest',
    'empathy',
    'admiration',
    'curiosity',
    'root_for',
    'protectiveness',
    'motion_expression_liking',
    'staging_liking',
    'character_craft_appreciation',
    'actual_similarity',
    'self_projection',
    'wishful_identification',
    'narrative_identification',
    'complementary_attraction',
    'vicarious_fulfillment',
    'parasocial_closeness',
    'companionship_desire',
    'guidance_seeking',
    'comfort_attachment',
    'long_term_attachment',
    'romantic_attraction',
    'sexual_attraction',
    'sympathy',
    'emotional_impact',
    'meaningful_appreciation',
    'humor_enjoyment',
    'identity_exploration',
    'escapist_immersion',
    'emotion_regulation',
    'motivation',
    'self_expansion',
    'moral_support',
    'fascination_with_transgression',
    'love_to_hate',
    'desire_no_redemption',
    'representation_affirmation',
    'identity_expression',
    'social_bonding',
    'creative_inspiration',
    'nostalgic_attachment',
    'fandom_support',
    'dark_character_liking',
    'villain_role_fascination',
    'menacing_aesthetic_liking',
    'dark_performance_liking',
    'dark_competence_admiration',
    'power_fantasy',
    'transgression_fascination',
    'moral_distance_appreciation',
    'dark_love_to_hate',
    'root_for_dark_side',
    'villain_pov_identification',
    'vicarious_transgression',
    'dominance_fascination',
    'controlled_state_fascination',
    'corruption_arc_fascination',
    'betrayal_fascination',
    'former_ally_tragedy',
    'identity_erosion_fascination',
    'inner_resistance_fascination',
    'surrender_fascination',
    'toxic_bond_fascination',
    'selective_tenderness_contrast',
    'fear_thrill',
    'dark_curiosity',
    'rescue_restore_desire',
    'preserve_dark_state',
    'no_redemption_preference',
    'dark_outcome_interest',
    'safe_taboo_exploration',
    'dark_romantic_attraction',
    'dark_sexual_attraction',
    'dark_creative_inspiration'
  )),
  strength REAL NOT NULL CHECK (strength BETWEEN 0.0 AND 1.0),
  explicitness TEXT NOT NULL CHECK (explicitness IN ('user_explicit','user_confirmed','inferred','model_knowledge')),
  confidence REAL NOT NULL CHECK (confidence BETWEEN 0.0 AND 1.0),
  context_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL CHECK (status IN ('proposed','confirmed','corrected','rejected','superseded')),
  superseded_by_id TEXT REFERENCES preference_assertions_new(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  CHECK (id <> superseded_by_id),
  CHECK (explicitness <> 'model_knowledge' OR confidence <= 0.45)
);

INSERT INTO preference_assertions_new SELECT * FROM preference_assertions;
DROP TABLE preference_assertions;
ALTER TABLE preference_assertions_new RENAME TO preference_assertions;

CREATE INDEX idx_preference_assertions_owner_status
  ON preference_assertions (owner_user_id,analysis_domain,status,attribute_definition_id,response_channel,id);
CREATE INDEX idx_preference_assertions_entry ON preference_assertions (entry_revision_id,created_at,id);

