export const responseChannelCategories = [
  { key: "expression", label: "見た目・声・表現", description: "どの表現要素に惹かれるか" },
  { key: "self_relation", label: "自分との重なり・同一化", description: "似ている、重ねる、なりたいを区別" },
  { key: "relationship", label: "親しさ・関係性", description: "別の相手として感じる親密さや関係の願望" },
  { key: "story_emotion", label: "物語・感情体験", description: "物語を通して生じる感情や鑑賞のしかた" },
  { key: "psychological_function", label: "自分への作用", description: "気分、自己理解、成長などへの作用" },
  { key: "values_ambivalence", label: "価値観・逸脱・複雑な好意", description: "支持、逸脱への魅力、嫌悪を含む楽しみ" },
  { key: "culture_fandom", label: "文化・ファンダム・創作", description: "表象、交流、創作や応援行動とのつながり" },
] as const;

export const responseChannelCatalog = [
  {
    value: "person_liking",
    label: "人物として好き",
    description: "その人物自体に好感がある",
    tier: "popular",
    category: "popular",
  },
  {
    value: "aesthetic_liking",
    label: "見た目・デザインが好き",
    description: "外見、衣装、色、造形などに惹かれる",
    tier: "popular",
    category: "popular",
  },
  {
    value: "voice_performance_liking",
    label: "声・話し方・演技が好き",
    description: "声質、口調、話速、演技などに惹かれる",
    tier: "popular",
    category: "popular",
  },
  {
    value: "narrative_interest",
    label: "物語を面白くする",
    description: "登場すると物語が面白くなる",
    tier: "popular",
    category: "popular",
  },
  {
    value: "empathy",
    label: "感情に共感する",
    description: "その人物と同じような感情になる",
    tier: "popular",
    category: "popular",
  },
  {
    value: "admiration",
    label: "尊敬する",
    description: "能力、生き方、姿勢などを高く評価する",
    tier: "popular",
    category: "popular",
  },
  {
    value: "curiosity",
    label: "もっと知りたい・気になる",
    description: "好感や支持とは別に、内面や行く末が気になる",
    tier: "popular",
    category: "popular",
  },
  {
    value: "root_for",
    label: "成功・勝利を応援したい",
    description: "善悪にかかわらず、望む結果を得てほしい",
    tier: "popular",
    category: "popular",
  },
  {
    value: "protectiveness",
    label: "守りたい・世話をしたい",
    description: "傷ついてほしくない、助けたいと感じる",
    tier: "popular",
    category: "popular",
  },
  {
    value: "motion_expression_liking",
    label: "表情・仕草・動きが好き",
    description: "姿勢、視線、表情、動作などに惹かれる",
    tier: "detail",
    category: "expression",
  },
  {
    value: "staging_liking",
    label: "演出・音楽・見せ方が好き",
    description: "カメラ、音楽、登場演出などによる魅力",
    tier: "detail",
    category: "expression",
  },
  {
    value: "character_craft_appreciation",
    label: "人物造形・描写の巧さを評価する",
    description: "設定や脚本、描写の組み立てを鑑賞している",
    tier: "detail",
    category: "expression",
  },
  {
    value: "actual_similarity",
    label: "自分に似ていると感じる",
    description: "性格、価値観、経験や境遇が近いと感じる",
    tier: "detail",
    category: "self_relation",
  },
  {
    value: "self_projection",
    label: "自分を重ねて見ている",
    description: "実際の類似とは別に、自分を投影して解釈する",
    tier: "detail",
    category: "self_relation",
  },
  {
    value: "wishful_identification",
    label: "この人物のようになりたい",
    description: "理想像として、同じように振る舞いたい",
    tier: "detail",
    category: "self_relation",
  },
  {
    value: "narrative_identification",
    label: "この人物の視点で物語を体験する",
    description: "物語中に視点、目標、感情を一時的に採用する",
    tier: "detail",
    category: "self_relation",
  },
  {
    value: "complementary_attraction",
    label: "自分にないものに惹かれる",
    description: "自分とは異なる性質や能力に補完的な魅力を感じる",
    tier: "detail",
    category: "self_relation",
  },
  {
    value: "vicarious_fulfillment",
    label: "自分にできないことを代わりにしてくれる",
    description: "行動、成功、反抗などを代理で経験する",
    tier: "detail",
    category: "self_relation",
  },
  {
    value: "parasocial_closeness",
    label: "友人・知人のように親しく感じる",
    description: "自分とは別の相手として継続的な親近感がある",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "companionship_desire",
    label: "一緒に過ごす・行動することを想像する",
    description: "会話、共同生活、共同行動などを望む",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "guidance_seeking",
    label: "頼りたい・ついていきたい",
    description: "導き、判断、保護などを委ねたいと感じる",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "comfort_attachment",
    label: "安心・慰めを感じる",
    description: "安全な存在、心の支えのように感じる",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "long_term_attachment",
    label: "長く大切に思い続けたい",
    description: "一時的な好みではない、持続的な愛着がある",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "romantic_attraction",
    label: "恋愛的に惹かれる",
    description: "恋愛関係を想像する、恋愛感情を抱く",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "sexual_attraction",
    label: "性的に惹かれる",
    description: "恋愛的な魅力とは別に性的な魅力を感じる",
    tier: "detail",
    category: "relationship",
  },
  {
    value: "sympathy",
    label: "心配・同情する",
    description: "同じ感情になる共感とは別に、相手を気遣う",
    tier: "detail",
    category: "story_emotion",
  },
  {
    value: "emotional_impact",
    label: "強く心を動かされる",
    description: "喜び、悲しみ、恐怖、驚きなどを強く喚起される",
    tier: "detail",
    category: "story_emotion",
  },
  {
    value: "meaningful_appreciation",
    label: "生き方やテーマを深く味わう",
    description: "楽しいだけでなく、意味や価値を考えさせられる",
    tier: "detail",
    category: "story_emotion",
  },
  {
    value: "humor_enjoyment",
    label: "笑わせてくれる",
    description: "言動、掛け合い、状況などの可笑しさを楽しむ",
    tier: "detail",
    category: "story_emotion",
  },
  {
    value: "identity_exploration",
    label: "自分らしさを考える助けになる",
    description: "自己像、価値観、アイデンティティを探索できる",
    tier: "detail",
    category: "psychological_function",
  },
  {
    value: "escapist_immersion",
    label: "現実を離れて没入できる",
    description: "日常から一時的に離れる体験を得る",
    tier: "detail",
    category: "psychological_function",
  },
  {
    value: "emotion_regulation",
    label: "気分を整えられる",
    description: "元気になる、落ち着く、気持ちを切り替えられる",
    tier: "detail",
    category: "psychological_function",
  },
  {
    value: "motivation",
    label: "頑張る力をもらえる",
    description: "行動や継続への意欲を引き出される",
    tier: "detail",
    category: "psychological_function",
  },
  {
    value: "self_expansion",
    label: "新しい視点や可能性に触れられる",
    description: "自分の世界、知識、できることが広がる感覚がある",
    tier: "detail",
    category: "psychological_function",
  },
  {
    value: "moral_support",
    label: "考え方・行動を支持する",
    description: "人物への好感とは別に、価値観や選択を支持する",
    tier: "detail",
    category: "values_ambivalence",
  },
  {
    value: "fascination_with_transgression",
    label: "逸脱や禁忌に惹かれる",
    description: "現実とは切り分けて、規範を越える姿を楽しむ",
    tier: "detail",
    category: "values_ambivalence",
  },
  {
    value: "love_to_hate",
    label: "嫌いな部分も含めて楽しい",
    description: "人物としての嫌悪と、キャラクターとしての魅力が共存する",
    tier: "detail",
    category: "values_ambivalence",
  },
  {
    value: "desire_no_redemption",
    label: "改心せずにいてほしい",
    description: "贖罪や善性の追加を望まず、そのあり方を保ってほしい",
    tier: "detail",
    category: "values_ambivalence",
  },
  {
    value: "representation_affirmation",
    label: "自分の文化・属性・経験の表象として大切",
    description: "自分や身近な集団が表現されていると感じる",
    tier: "detail",
    category: "culture_fandom",
  },
  {
    value: "identity_expression",
    label: "好きであることが自分らしさの表現になる",
    description: "その人物への好意を自分のアイデンティティとして示す",
    tier: "detail",
    category: "culture_fandom",
  },
  {
    value: "social_bonding",
    label: "他のファンとのつながりが生まれる",
    description: "会話、共有、コミュニティ参加を通じて人と結びつく",
    tier: "detail",
    category: "culture_fandom",
  },
  {
    value: "creative_inspiration",
    label: "創作したくなる",
    description: "絵、文章、考察、コスプレなどの創作意欲が湧く",
    tier: "detail",
    category: "culture_fandom",
  },
  {
    value: "nostalgic_attachment",
    label: "思い出・懐かしさと結びついている",
    description: "過去の時期、体験、人間関係などを思い出す",
    tier: "detail",
    category: "culture_fandom",
  },
  {
    value: "fandom_support",
    label: "投票・購入などで応援したい",
    description: "投票、グッズ購入、紹介などの行動で支えたい",
    tier: "detail",
    category: "culture_fandom",
  },
] as const;

export type ResponseChannel = (typeof responseChannelCatalog)[number]["value"];
export const responseChannelValues = responseChannelCatalog.map((item) => item.value) as [
  ResponseChannel,
  ...ResponseChannel[],
];

const responseChannelByValue = new Map<string, (typeof responseChannelCatalog)[number]>(
  responseChannelCatalog.map((item) => [item.value, item]),
);

export function responseChannelLabel(value: string): string {
  return responseChannelByValue.get(value)?.label ?? "その他の反応";
}

export function responseChannelPrompt(): string {
  return responseChannelCatalog.map((item) => `${item.value}: ${item.label} — ${item.description}`).join("\n");
}
